name: Update_Idealista

on:
  schedule:
    - cron: "10 9 * * *"   # Ejecuta todos los días a las 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python update_idealista.py

      - name: Commit and push CSV
        run: |
          git config --global user.name "AlbertPoloMolina"
          git config --global user.email "apolomo@uoc.edu"
          git add historial_idealista.csv
          git commit -m "Update CSV [skip ci]" || echo "No changes to commit"
          git push
